repos:
- repo: https://github.com/asottile/reorder_python_imports
  rev: v1.3.5
  hooks:
  - id: reorder-python-imports
    args:
    - --application-directories=.:src

- repo: https://github.com/grktsh/ffffff
  rev: v2018.11.15
  hooks:
  - id: ffffff

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.5
  hooks:
  - id: flake8

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.1.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
